language: go
sudo: false
go:
  -1.9.x
  -1.10.x
  -master

before_install:
  - go get github.com/wadey/gocovmerge
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - go get -d -v $(go list)

script:
  - go test -v $(go list)

after_success:
  - bash .generate_coverage.sh
  - goveralls -coverprofile=full_cov.out -service=travis-ci
