// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/LemoFoundationLtd/lemochain-core/common"
	"github.com/LemoFoundationLtd/lemochain-core/common/hexutil"
)

var _ = (*assetEquityMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (a AssetEquity) MarshalJSON() ([]byte, error) {
	type AssetEquity struct {
		AssetCode common.Hash    `json:"assetCode" gencodec:"required"`
		AssetId   common.Hash    `json:"assetId" gencodec:"required"`
		Equity    *hexutil.Big10 `json:"equity" gencodec:"required"`
	}
	var enc AssetEquity
	enc.AssetCode = a.AssetCode
	enc.AssetId = a.AssetId
	enc.Equity = (*hexutil.Big10)(a.Equity)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *AssetEquity) UnmarshalJSON(input []byte) error {
	type AssetEquity struct {
		AssetCode *common.Hash   `json:"assetCode" gencodec:"required"`
		AssetId   *common.Hash   `json:"assetId" gencodec:"required"`
		Equity    *hexutil.Big10 `json:"equity" gencodec:"required"`
	}
	var dec AssetEquity
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.AssetCode == nil {
		return errors.New("missing required field 'assetCode' for AssetEquity")
	}
	a.AssetCode = *dec.AssetCode
	if dec.AssetId == nil {
		return errors.New("missing required field 'assetId' for AssetEquity")
	}
	a.AssetId = *dec.AssetId
	if dec.Equity == nil {
		return errors.New("missing required field 'equity' for AssetEquity")
	}
	a.Equity = (*big.Int)(dec.Equity)
	return nil
}
