// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
)

// MarshalJSON marshals as JSON.
func (b Box) MarshalJSON() ([]byte, error) {
	type Box struct {
		SubTxList Transactions `json:"subTxList"  gencodec:"required"`
	}
	var enc Box
	enc.SubTxList = b.SubTxList
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (b *Box) UnmarshalJSON(input []byte) error {
	type Box struct {
		SubTxList *Transactions `json:"subTxList"  gencodec:"required"`
	}
	var dec Box
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.SubTxList == nil {
		return errors.New("missing required field 'subTxList' for Box")
	}
	b.SubTxList = *dec.SubTxList
	return nil
}
