// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"github.com/LemoFoundationLtd/lemochain-core/common"
)

// MarshalJSON marshals as JSON.
func (m ModifyAssetInfo) MarshalJSON() ([]byte, error) {
	type ModifyAssetInfo struct {
		AssetCode     common.Hash `json:"assetCode" gencodec:"required"`
		UpdateProfile Profile     `json:"updateProfile" gencodec:"required"`
	}
	var enc ModifyAssetInfo
	enc.AssetCode = m.AssetCode
	enc.UpdateProfile = m.UpdateProfile
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (m *ModifyAssetInfo) UnmarshalJSON(input []byte) error {
	type ModifyAssetInfo struct {
		AssetCode     *common.Hash `json:"assetCode" gencodec:"required"`
		UpdateProfile *Profile     `json:"updateProfile" gencodec:"required"`
	}
	var dec ModifyAssetInfo
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.AssetCode == nil {
		return errors.New("missing required field 'assetCode' for ModifyAssetInfo")
	}
	m.AssetCode = *dec.AssetCode
	if dec.UpdateProfile == nil {
		return errors.New("missing required field 'updateProfile' for ModifyAssetInfo")
	}
	m.UpdateProfile = *dec.UpdateProfile
	return nil
}
