// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/LemoFoundationLtd/lemochain-core/common"
	"github.com/LemoFoundationLtd/lemochain-core/common/hexutil"
)

var _ = (*transferAssetMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t TransferAsset) MarshalJSON() ([]byte, error) {
	type TransferAsset struct {
		AssetId common.Hash    `json:"assetId" gencodec:"required"`
		Amount  *hexutil.Big10 `json:"transferAmount" gencodec:"required"`
		Input   []byte         `json:"input"`
	}
	var enc TransferAsset
	enc.AssetId = t.AssetId
	enc.Amount = (*hexutil.Big10)(t.Amount)
	enc.Input = t.Input
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *TransferAsset) UnmarshalJSON(input []byte) error {
	type TransferAsset struct {
		AssetId *common.Hash   `json:"assetId" gencodec:"required"`
		Amount  *hexutil.Big10 `json:"transferAmount" gencodec:"required"`
		Input   []byte         `json:"input"`
	}
	var dec TransferAsset
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.AssetId == nil {
		return errors.New("missing required field 'assetId' for TransferAsset")
	}
	t.AssetId = *dec.AssetId
	if dec.Amount == nil {
		return errors.New("missing required field 'transferAmount' for TransferAsset")
	}
	t.Amount = (*big.Int)(dec.Amount)
	if dec.Input != nil {
		t.Input = dec.Input
	}
	return nil
}
