// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package store

import (
	"encoding/json"
	"errors"

	"github.com/LemoFoundationLtd/lemochain-core/chain/types"
	"github.com/LemoFoundationLtd/lemochain-core/common"
	"github.com/LemoFoundationLtd/lemochain-core/common/hexutil"
)

var _ = (*vTransactionMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (v VTransaction) MarshalJSON() ([]byte, error) {
	type VTransaction struct {
		Tx          *types.Transaction `json:"tx" gencodec:"required"`
		PHash       common.Hash        `json:"pHash" gencodec:"required"`
		PackageTime hexutil.Uint32     `json:"time" gencodec:"required"`
	}
	var enc VTransaction
	enc.Tx = v.Tx
	enc.PHash = v.PHash
	enc.PackageTime = hexutil.Uint32(v.PackageTime)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (v *VTransaction) UnmarshalJSON(input []byte) error {
	type VTransaction struct {
		Tx          *types.Transaction `json:"tx" gencodec:"required"`
		PHash       *common.Hash       `json:"pHash"`
		PackageTime *hexutil.Uint32    `json:"time" gencodec:"required"`
	}
	var dec VTransaction
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Tx == nil {
		return errors.New("missing required field 'tx' for VTransaction")
	}
	v.Tx = dec.Tx
	if dec.PHash == nil {
		return errors.New("missing required field 'pHash' for VTransaction")
	}
	v.PHash = *dec.PHash
	if dec.PackageTime == nil {
		return errors.New("missing required field 'time' for VTransaction")
	}
	v.PackageTime = uint32(*dec.PackageTime)
	return nil
}
