package common

const (
	DataDir          = "datadir"
	NetworkID        = "networkid"
	MaxPeers         = "maxpeers"
	ListenPort       = "port"
	ExtraData        = "extradata"
	NodeKeyFile      = "nodekey"
	MiningEnabled    = "mine"
	RPCEnabled       = "rpc"
	RPCListenAddr    = "rpcaddr"
	RPCPort          = "rpcport"
	RPCCORSDomain    = "rpccorsdomain"
	RPCVirtualHosts  = "rpcvhosts"
	RPCApi           = "rpcapi"
	IPCDisabled      = "ipcdisable"
	IPCPath          = "ipcpath"
	WSEnabled        = "ws"
	WSListenAddr     = "wsaddr"
	WSPort           = "wsport"
	WSApi            = "wsapi"
	WSAllowedOrigins = "wsorigins"
	Debug            = "debug"
	JSpath           = "jspath"
	LogLevel         = "loglevel"
)
