// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package transaction

import (
	"encoding/json"
	"errors"

	"github.com/LemoFoundationLtd/lemochain-core/chain/types"
)

// MarshalJSON marshals as JSON.
func (m ModifySigners) MarshalJSON() ([]byte, error) {
	type ModifySigners struct {
		Signers types.Signers `json:"signers"  gencodec:"required"`
	}
	var enc ModifySigners
	enc.Signers = m.Signers
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (m *ModifySigners) UnmarshalJSON(input []byte) error {
	type ModifySigners struct {
		Signers *types.Signers `json:"signers"  gencodec:"required"`
	}
	var dec ModifySigners
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Signers == nil {
		return errors.New("missing required field 'signers' for ModifySigners")
	}
	m.Signers = *dec.Signers
	return nil
}
