// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package chain

import (
	"encoding/json"
	"errors"

	"github.com/LemoFoundationLtd/lemochain-go/chain/deputynode"
	"github.com/LemoFoundationLtd/lemochain-go/common"
	"github.com/LemoFoundationLtd/lemochain-go/common/hexutil"
	"github.com/LemoFoundationLtd/lemochain-go/common/math"
)

var _ = (*genesisSpecMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g Genesis) MarshalJSON() ([]byte, error) {
	type Genesis struct {
		Time        math.HexOrDecimal64      `json:"timestamp"   gencodec:"required"`
		ExtraData   hexutil.Bytes            `json:"extraData"`
		GasLimit    math.HexOrDecimal64      `json:"gasLimit"    gencodec:"required"`
		LemoBase    common.Address           `json:"lemoBase"    gencodec:"required"`
		DeputyNodes []*deputynode.DeputyNode `json:"deputyNodes" gencodec:"required"`
	}
	var enc Genesis
	enc.Time = math.HexOrDecimal64(g.Time)
	enc.ExtraData = g.ExtraData
	enc.GasLimit = math.HexOrDecimal64(g.GasLimit)
	enc.LemoBase = g.LemoBase
	enc.DeputyNodes = g.DeputyNodes
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *Genesis) UnmarshalJSON(input []byte) error {
	type Genesis struct {
		Time        *math.HexOrDecimal64     `json:"timestamp"   gencodec:"required"`
		ExtraData   *hexutil.Bytes           `json:"extraData"`
		GasLimit    *math.HexOrDecimal64     `json:"gasLimit"    gencodec:"required"`
		LemoBase    *common.Address          `json:"lemoBase"    gencodec:"required"`
		DeputyNodes []*deputynode.DeputyNode `json:"deputyNodes" gencodec:"required"`
	}
	var dec Genesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Time == nil {
		return errors.New("missing required field 'timestamp' for Genesis")
	}
	g.Time = uint64(*dec.Time)
	if dec.ExtraData != nil {
		g.ExtraData = *dec.ExtraData
	}
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for Genesis")
	}
	g.GasLimit = uint64(*dec.GasLimit)
	if dec.LemoBase == nil {
		return errors.New("missing required field 'lemoBase' for Genesis")
	}
	g.LemoBase = *dec.LemoBase
	if dec.DeputyNodes == nil {
		return errors.New("missing required field 'deputyNodes' for Genesis")
	}
	g.DeputyNodes = dec.DeputyNodes
	return nil
}
