// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package params

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/LemoFoundationLtd/lemochain-go/common/hexutil"
)

var _ = (*RewardMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r Reward) MarshalJSON() ([]byte, error) {
	type Reward struct {
		Term  hexutil.Uint32 `json:"term" gencodec:"required"`
		Value *hexutil.Big10 `json:"value" gencodec:"required"`
		Times hexutil.Uint32 `json:"times" gencodec:"required"`
	}
	var enc Reward
	enc.Term = hexutil.Uint32(r.Term)
	enc.Value = (*hexutil.Big10)(r.Value)
	enc.Times = hexutil.Uint32(r.Times)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *Reward) UnmarshalJSON(input []byte) error {
	type Reward struct {
		Term  *hexutil.Uint32 `json:"term" gencodec:"required"`
		Value *hexutil.Big10  `json:"value" gencodec:"required"`
		Times *hexutil.Uint32 `json:"times" gencodec:"required"`
	}
	var dec Reward
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Term == nil {
		return errors.New("missing required field 'term' for Reward")
	}
	r.Term = uint32(*dec.Term)
	if dec.Value == nil {
		return errors.New("missing required field 'value' for Reward")
	}
	r.Value = (*big.Int)(dec.Value)
	if dec.Times == nil {
		return errors.New("missing required field 'times' for Reward")
	}
	r.Times = uint32(*dec.Times)
	return nil
}
