// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package params

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/LemoFoundationLtd/lemochain-go/common/hexutil"
)

var _ = (*RewardJsonMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r RewardJson) MarshalJSON() ([]byte, error) {
	type RewardJson struct {
		Term  hexutil.Uint32 `json:"term" gencodec:"required"`
		Value *hexutil.Big10 `json:"value" gencodec:"required"`
	}
	var enc RewardJson
	enc.Term = hexutil.Uint32(r.Term)
	enc.Value = (*hexutil.Big10)(r.Value)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *RewardJson) UnmarshalJSON(input []byte) error {
	type RewardJson struct {
		Term  *hexutil.Uint32 `json:"term" gencodec:"required"`
		Value *hexutil.Big10  `json:"value" gencodec:"required"`
	}
	var dec RewardJson
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Term == nil {
		return errors.New("missing required field 'term' for RewardJson")
	}
	r.Term = uint32(*dec.Term)
	if dec.Value == nil {
		return errors.New("missing required field 'value' for RewardJson")
	}
	r.Value = (*big.Int)(dec.Value)
	return nil
}
